static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
      - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            idle_timeout: 3s
            access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
            cluster: redis
            stat_prefix: redis
  clusters:
  - name: redis
    connect_timeout: 15s
    type: strict_dns
    transport_socket:
      name: envoy.transport_sockets.raw_buffer
    load_assignment:
      cluster_name: redis
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.18.0.4
                port_value: 6379         
